BaSP-a2022/ayom-b-trackgenix-server

.vscode/settings.json, Readme.md, src/data/projects.json, src/index.js, src/resources/projects.js
1. Update the readme.
2. Create the projects.json .
3. Create logic to get projects by id.
4. Create logic to create new projects.
5. Create logic to delete projects.
=> BaSP-TG: Projects method (GET-DELETE-POST)

package-lock.json, package.json, postman_collection.json, src/index.js
Create the working environment to start working on the issue.
=> BaSP-TG-1: Set up the environment

postman_collection.json, src/controllers/admins.js, src/index.js, src/models/Admins.js, src/routes/admins.js, src/validations/admins.js
Create:
-  Admin Schema
- admin routes to:
- - Get by Id
- - Delete by Id
- - Edit Admin by Id
=> BaSP-TG-3: Create methods and resources to Admin

postman_collection.json, src/controllers/tasks.js, src/index.js, src/models/Tasks.js, src/routes/tasks.js, src/validations/tasks.js
Create Task Component.
That include Get All tasks, and Create task router's method.
=> BaSP-TG-7: Task endpoints get all, and create methods

postman_collection.json, src/controllers/admins.js, src/index.js, src/models/Admins.js, src/routes/admins.js, src/validations/admins.js
Created:
- Admin schema together with Juli
- Admin endpoints for: GetAll and Create admin
=> BaSP-TG-04: Admin endpoints (GetAll and Create)

src/controllers/projects.js, src/index.js, src/routes/projects.js
getAll and create endpoints were added
=> BaSP-TG-20: Add missing endpoints

.husky/pre-commit, src/controllers/timeSheets.js, src/models/TimeSheets.js
Updated the timesheet schema to establish a relationship between some of its properties and other models.
Updated the controllers with the populate method so as to fill the timesheet model with the models and their data
=> BaSP-TG-22: Update Timesheet schemas and controllers

src/validations/timeSheets.js
A new validation was generated in order to contemplate the new fields required in the timeSheet models.
Please consider and comment to improve the connectivity between models in the Joi schemas.
=> BaSP-TG-40: Update TimeSheet valdiations

src/controllers/employees.js, src/tests/employees.test.js
Added unit test for:
- Get Employee By Id
- Create Employee
- Delete Employee
=> BaSP-TG-34: Employee Unit Testing (POST-DELETE-GET BY ID)

src/controllers/tasks.js, src/tests/tasks.test.js, src/tests/tesks.test.js, src/validations/timeSheets.js
I correct some errors in the controllers, like HTTP responses and added errors (true or false) in response body (json).
I added the tests for task Delete and Get all methods.
=> BaSP-TG-25: Task unit test - Delete - Get All

src/controllers/admins.js, src/tests/admins.test.js
=> BaSP-TG-30: Admin unit test

src/controllers/superAdmins.js, src/tests/superAdmins.test.js
I correct some errors in the controllers, added new functionalities with new HTTP responses and added errors (true or false) in response body (json).
I added the tests for task Delete and Get by ID methods.
=> BaSP-TG-24: Super Admin unit test - Delete - Get by ID

src/seeds/superAdmins.js, src/tests/superAdmins.test.js
- GET all with filters
- EDIT
- CREATE
=> BaSP-TG-31: SuperAdmins Unit Tests

src/controllers/employees.js, src/tests/employees.test.js
Added Tests for employee: GetAll Employees and Edit an Employee
=> BaSP-TG-37: Added Get and Edit Test of Employee

src/controllers/admins.js, src/tests/admins.test.js
Added Tests for Admin: GetAll Employees and Create an Admin
=> BaSP-TG-23: Added GetAll and Create Test  of Admin

package-lock.json, package.json, src/app.js
=> BaSP-TG-47:Import Cors

src/validations/projects.js
1) End Date now must be higher than Start Date to be valid
2) Name, Client Name, Description no longer allows it to be completed with only blank spaces, only numbers or only special characters. The Empty spaces at the edges do not count to the minimum of 3 characters
3) Rate now must be a positive number ( greater than 0: number > 0). No longer allows negative numbers
=> BaSP-TG-72: FIX Project validations

src/controllers/employees.js, src/tests/employees.test.js
Change the status code 200 to 201 on the post method and changed the test message and expected status
=> BaSP-TG-67:post method status code and test fixed

src/controllers/admins.js, src/controllers/employees.js, src/controllers/projects.js, src/controllers/superAdmins.js, src/controllers/tasks.js, src/controllers/timeSheets.js, src/tests/admins.test.js, src/tests/employees.test.js, src/tests/projects.test.js, src/tests/superAdmins.test.js, src/tests/tasks.test.js, src/tests/timeSheets.test.js
CHANGE all entities to send status 200 when fetching an empty list.
RE-ARRANGE test to validate the new status and messages
=> BaSP-TG-53: CHANGE GetAll method returns 200 when list is empty

src/controllers/admins.js, src/tests/admins.test.js
1. getById method was returning status 200 for non-existent Ids in the DB
2. Also included a validation for a correct Id format (to be a mongoose type)
=> BaSP-TG-54: Fix getById method for Admins entity

src/models/Tasks.js, src/tests/tasks.test.js, src/validations/tasks.js, src/validations/timeSheets.js
**Task description validation:**
- Description now can be a string of only letters, with a minimum of 3
- Descriptions must be unique
=> BaSP-TG-77: Changed task description validation

jest.config.js, src/controllers/admins.js, src/controllers/employees.js, src/controllers/projects.js, src/controllers/superAdmins.js, src/controllers/tasks.js, src/controllers/timeSheets.js, src/tests/admins.test.js, src/tests/projects.test.js, src/tests/superAdmins.test.js
Added a function in all controllers to check if the used id for the request is a valid mongoDB id. 
Also fixed all test that stopped working with these changes
=> BaSP-TG-55: Added check for valid id

src/tests/tasks.test.js, src/validations/admins.js, src/validations/employees.js, src/validations/projects.js, src/validations/superAdmins.js, src/validations/tasks.js, src/validations/timeSheets.js
Added error: true to all JOI validations
=> BaSP-TG-106: Code optimization

src/controllers/admins.js, src/controllers/employees.js, src/controllers/projects.js, src/controllers/superAdmins.js, src/controllers/tasks.js, src/controllers/timeSheets.js, src/tests/admins.test.js, src/tests/employees.test.js, src/tests/projects.test.js, src/tests/superAdmins.test.js, src/tests/tasks.test.js
Fix Bugs from:
- TG-82
- TG-83
- TG-85
- TG-86
- TG-87
- TG-88
- TG-89
- TG-90
=> BaSP-TG-128: FIX backend bugs

postman_collection.json, src/controllers/projects.js, src/routes/projects.js, src/tests/projects.test.js, src/validations/tasks.js
Add new endpoint to get all projects by employee ID inside the project
=> BaSP-TG-118: Employee Projects Page

postman_collection.json, src/controllers/timeSheets.js, src/routes/timeSheets.js, src/tests/timeSheets.test.js
Added a endpoint to get all the timesheets that an employee is part of
Work by Cristian Gerster and Maicol Freire
=> BaSP-TG-119: Get timesheets by employee id

.husky/pre-commit, package-lock.json, package.json, src/Helpers/Firebase/index.js, src/controllers/admins.js, src/controllers/employees.js, src/controllers/superAdmins.js, src/middlewares/authMiddleware.js, src/models/Admins.js, src/models/Employees.js, src/models/SuperAdmins.js, src/routes/admins.js, src/routes/employees.js, src/routes/projects.js, src/routes/superAdmins.js, src/routes/tasks.js, src/routes/timeSheets.js
In this PR the following was done:
- Setup firebase service keys.
- Create middleware function.
- Add middleware to routes.
- Implemented firebase in Admins, Employees and Super Admins entities.
=> BaSP-TG-135: implement firebase in server

src/controllers/admins.js, src/controllers/employees.js, src/controllers/superAdmins.js
- Fixed firebaseUid parsing in delete, edit and create methods for employees, admins and superadmins.
=> BaSP-TG-138: fixed backend

src/controllers/admins.js, src/controllers/employees.js, src/controllers/superAdmins.js, src/routes/admins.js, src/routes/employees.js, src/routes/superAdmins.js
ADD new endpoints to search by firebaseUid employee, admin and superAdmin
=> BaSP-TG-153: ADD new endpoints to find by firebaseUid

src/controllers/tasks.js
Fixed delete method in tasks entity.
=> BaSP-TG-164: fixed tasks delete method
